// Generated by @qlik/dts-bundler@development

import { OtherLib } from "other-lib";

export interface Combined {
  local: AnotherLocalHelper;
  otherLocal: AdditionalLocalHelper;
  yetAnotherLocal: YetAnotherLocalHelper;
  lib: LibType;
  other: OtherLib;
}
