// Generated by @qlik/dts-bundler@development

import type { Config } from "another-package";
import type { Config as Config2 } from "external-package";
/**
 * A Local helper type for internal use.
 */
type LocalHelper = {
  help(): void;
};
type AnotherLocalHelper = {
  assist(): void;
  config: Config;
};
export type AdditionalLocalHelper = {
  configure(): void;
  settings: Config2;
};
// @ts-expect-error - test case for external lib types
import { OtherLib } from "other-lib";
import type { Config as Config3 } from "third-package";
/**
 * A Local helper type for internal use.
 */
export type YetAnotherLocalHelper = {
  setup(): void;
  configuration: Config3;
};
export interface Combined {
  local: AnotherLocalHelper;
  otherLocal: AdditionalLocalHelper;
  yetAnotherLocal: YetAnotherLocalHelper;
  lib: LibType;
  other: OtherLib;
}
