// Generated by @qlik/dts-bundler@development

type OpenProps = {
  reason: "inTab" | "newWindow" | "modal";
};
type CloseProps = {
  reason: "escape" | "backdrop";
};
declare global {
  interface PrivateQlikEmbedProps {
    /** Typically not used */
    allowPrivateUnsupportedInternalQlikUIs?: boolean;
    /** Typically not used */
    close?: (closeProps: unknown) => unknown;
    /** If embedding is running in an iframe */
    qmfeEmbedIframed?: boolean;
    onLoading?: () => void;
    /**
    * Called when the parcel reports readiness via `reportReady()`, or immediately after mount
    * if `reportsReadiness` is not set.
    * Indicates the parcel is ready to be shown to users to reduce flickering on load.
    *
    * @example
    * ```ts
    * // Parcel definition
    * export const Chart = qmfeReactParcel({
    *   lazyComponent: () => import("./parcels/Chart"),
    *   reportsReadiness: true,
    * });
    *
    * // Inside the parcel component
    * export default function Chart(props: QmfeParcelProps<"charts/Chart">) {
    *   const { reportReady } = props;
    *   const { data } = useQuery({ queryKey: ["chart-data"], queryFn: fetchChartData });
    *
    *   useLayoutEffect(() => {
    *     if (data) {
    *       reportReady();
    *     }
    *   }, [data, reportReady]);
    *
    *   return <div>Chart UI</div>;
    * }
    * ```
    */
    onReady?: () => void;
    /**
    * Called when the parcel reports steadiness via `reportSteady()`, or immediately after mount
    * if `reportsSteadiness` is not set.
    * Indicates everything inside the parcel has finished loading, animations have completed, and the DOM is steady.
    *
    * @example
    * ```ts
    * // Parcel definition
    * export const Chart = qmfeReactParcel({
    *   lazyComponent: () => import("./parcels/Chart"),
    *   reportsSteadiness: true,
    * });
    *
    * // Inside the parcel component
    * export default function Chart(props: QmfeParcelProps<"charts/Chart">) {
    *   const { reportSteady } = props;
    *   const [animationComplete, setAnimationComplete] = useState(false);
    *
    *   useLayoutEffect(() => {
    *     // Wait for animations to complete or other components to finish loading their data
    *     if (animationComplete) {
    *       reportSteady();
    *     }
    *   }, [animationComplete, reportSteady]);
    *
    *   return <div>Chart UI</div>;
    * }
    * ```
    */
    onSteady?: () => void;
    /**
    * @experimental
    */
    updateWrapperProps?: (props: Record<string, unknown>) => void;
  }
}
declare global {
  interface QlikEmbedUIs {
    "ui-kit/ConfirmDialog": {
      props: {
        type: "confirm" | "delete";
        actionText: string;
        /** defaults to a localized 'Cancel' */
        cancelText?: string;
        content: string;
        doNotShowAgainKey?: string;
        onConfirm?: () => Promise<void>;
        onCancel: () => void;
      };
    };
    "ui-kit/ModalWrapper": {
      props: {
        /** parcel to show in the modal container */
        content?: string;
        /** adds a modal title to the top of the modal element */
        title?: string;
        /** adds a description below the title */
        description?: string;
        /**
        * Minimum height of the modal container. Once the parcel gets rendered it will fit the size of that content.
        * Can be used to reduce layout shifting since the height of the modal is not know until the parcel is rendered.
        */
        height?: string;
        /**
        * Disable padding on the modal content. This is useful for when the parcel has its own padding and
        * you want to avoid double padding.
        * @experimental
        */
        noPadding?: boolean;
      };
    };
    "ui-kit/Menu": {
      props: OpenProps;
    };
    "ui-kit/PopoverWrapper": {
      props: {
        /** The element to anchor the popover to */
        anchorEl?: HTMLElement;
        /** The position of the popover */
        anchorPosition?: {
          top: number;
          left: number;
        };
        /** The popover content */
        content?: string;
      };
    };
  }
}
export interface MenuProps {
  onClose: (props: CloseProps) => void;
  onOpen: (props: OpenProps) => void;
}
declare global {
  interface UIRegistry {
    Menu: MenuProps;
  }
}
