// Generated by @qlik/dts-bundler@development

type OtherProp = {
  value: number;
};
type ParcelProps = {
  /** The DOM element or selector where the parcel will be mounted */
  mountPoint: HTMLElement | string;
  /** Props passed to the parcel */
  props?: Record<string, unknown>;
};
export type OutputType = {
  other: OtherProp;
  parcel: ParcelProps;
};
