// Generated by @qlik/dts-bundler@development

interface Helper {
  assist: () => void;

}
type IKnowWhatImDoing = any;
type OkiDoki = IKnowWhatImDoing;
export interface User {
  id: IKnowWhatImDoing;
  name: OkiDoki;
  helper: Helper;
}
