// Generated by @qlik/dts-bundler@development

type CloseProps = {
  reason: "escape" | "backdrop";
};
export interface MenuProps {
  onClose: (props: CloseProps) => void;
}
declare global {
  interface UIRegistry {
    Menu: MenuProps;
  }
}
