// Generated by @qlik/dts-bundler@development

export type UserStatus = MyStatus;
export type ApiResponse<T> = MyResult<T>;
export type RunnerStatus = Status;
export type RunnerResponse<T> = Result<T>;
export interface Config {
  status: MyStatus;
}
