// Generated by @qlik/dts-bundler@development

declare const defaultExportedString = "str",
  justExportedNumber = 123;
export declare const exportedString = "str";

export { defaultExportedString as default };

export {};
