// Generated by @qlik/dts-bundler@development

type Status = "pending" | "active" | "completed";
type Result<T> = { success: true; data: T } | { success: false; error: string };
export type UserStatus = Status;
export type ApiResponse<T> = Result<T>;
export interface Config {
  status: Status;
}