// Generated by @qlik/dts-bundler@0.0.1

import type { TypeOnly } from "another-package";
import type { SomeType } from "external-package";

export interface MyType {
  data: SomeType;
  other: TypeOnly;
}