// Generated by @qlik/dts-bundler@development

import { OtherLib } from "other-lib";

/**
 * A Local helper type for internal use.
 */
type LocalHelper = {
  help(): void;
};
export interface Combined {
  local: LocalHelper;
  lib: LibType;
  other: OtherLib;
}