// Generated by @qlik/dts-bundler@development

type MyStatus = "pending" | "active" | "completed";
type MyResult<T> = { success: true; data: T } | { success: false; error: string };
type Status = "staring" | "ongoing" | "ended";
type Result<T> = { failure: true; data: T } | { failure: false; error: string };
export type UserStatus = MyStatus;
export type ApiResponse<T> = MyResult<T>;
export type RunnerStatus = Status;
export type RunnerResponse<T> = Result<T>;
export interface Config {
  status: MyStatus;
}