// Generated by @qlik/dts-bundler@development

import * as fakePackage from "fake-package";
import {
  Interface as FPI1,
  Interface as FPI2,
  Interface as Interface$2,
} from "fake-package";

declare namespace NamespaceName {
  interface Local {}
}
declare const MergedSymbol = "";
declare var Variable = 1;
interface MergedSymbol {
  test(): void;
}
interface Interface {
  field1: number;
}
declare function func(one: number);
type TypeName = Pick<Interface, "field1">;
interface AnotherInterface$1 {
  field1: number;
}
declare namespace NamespaceName {
  interface Local {}
}
declare function anotherFunc$1(one: NamespaceName.Local);
declare const MergedSymbol$1 = "";
declare var Variable$1 = "";
interface MergedSymbol$1 {
  test(): void;
}
interface Interface$1 {
  field2: number;
}
declare function func$1(two: number);
type TypeName$1 = Pick<Interface$1, "field2">;
interface ExportedButNotUsedInterface {}
declare namespace ExportEqNs {
  namespace InternalNs {
    type NewType = string;
  }
  type Bar = ExportEqNs$1.Foo;
  type Foo = String;
  namespace InternalNs2 {
    type Type21 = InternalNs3.Type31;
    type Type22 = InternalNs2.InternalNs3.Type31;
    type Type23 = ExportEqNs$1.InternalNs2.InternalNs3.Type31;
    namespace InternalNs3 {
      type Type31 = InternalNs4.Type;
      type Type32 = InternalNs3.InternalNs4.Type;
      type Type33 = InternalNs2.InternalNs3.InternalNs4.Type;
      type Type34 = ExportEqNs$1.InternalNs2.InternalNs3.InternalNs4.Type;
      namespace InternalNs4 {
        type Type = string;
      }
    }
  }
}
export type ExportEqNs = string;
declare const TEMPLATE = "template1";
declare const TEMPLATE$1 = "template2";
/** Another interface doc string */
export interface AnotherInterface {
  field2: number;
}
/** Another func doc string */
export declare function anotherFunc(two: NamespaceName$1.Local);
export interface Inter {
  field: Interface;
  field2: AnotherInterface;
  field3: TypeName;
  field4: AnotherInterface$1;
  field5: fakePackage.Interface$2;
  field6: FPI1;
  field7: Interface$2;
}
interface DefaultInterface {
  field10: number;
}
export interface Inter2 {
  field: Interface;
  field2: AnotherInterface;
  field3: TypeName;
  field4: AnotherInterface$1;
  field5: fakePackage.Interface$2;
  field6: FPI2;
  field7: Interface$2;
  field8: DefaultInterface;
}
export type MyType = Interface$2;
export type ExportedNsType = ExportEqNs$1.InternalNs.NewType;

export {
  anotherFunc as af1,
  AnotherInterface as AI1,
  func as f1,
  func as f2,
  Interface as I1,
  Interface as I2,
  MergedSymbol as MS1,
  MergedSymbol as MS2,
  NamespaceName as NS1,
  NamespaceName as NS2,
  TypeName as T1,
  TypeName as T2,
  TEMPLATE as TEMPLATE1,
  TEMPLATE as TEMPLATE2,
  Variable as V1,
  Variable as V2,
};
