// Generated by @qlik/dts-bundler@development

type SecondType<T, V> = T extends any ? V : FirstType<T>;
type ThirdType = number;
type FirstType<T> = SecondType<ThirdType, T>;
export type MyType = FirstType<string>;
