// Generated by @qlik/dts-bundler@development

export { Interface as Interface2, InterfaceWithFields } from "fake-package";
export { ReExportedName as NewReExportedName } from "package-with-re-exports";
import {
  NonDefaultInterface as Foo,
  NonDefaultInterface,
  NonDefaultInterface as Type,
} from "package-with-default-export";

type Foo$1 = string;
export type Bar = Foo$1;

export { Foo, NonDefaultInterface, Type };
