// Generated by @qlik/dts-bundler@development

import { NonDefaultInterface as DFI } from "package-with-default-export";

interface CustomType {
  foo: number;
  bar: string;
}
declare namespace Namespace {
  const baz: number;
}
declare type GenericType<T, U> = {};
export interface Interface {}
declare namespace Namespace$1 {
  const baz: number;
}
interface MyType {
  field: CustomType;
  field2: typeof Namespace$1;
  field3: import("ora").Options;
  field4: GenericType<number, string>;
  field5: Interface;
  field6: typeof Namespace$1;
  field7: import("package-with-default-export").NonDefaultInterface;
}
export type MySecondType = MyType | number | DFI;
