// Generated by @qlik/dts-bundler@development

type FooBar = string;
declare namespace F1Ns1 {
  namespace SubNs1 {
    interface Interface1 {
      field1: FooBar;
    }
  }
}
declare namespace F1Ns1 {
  namespace SubNs1 {
    interface Interface2 {
      field1: FooBar;
    }
  }
}
type FooBar$1 = number;
declare namespace F2Ns1 {
  namespace SubNs1 {
    interface Interface1 {
      field1: FooBar$1;
    }
  }
}
declare namespace F2Ns1 {
  namespace SubNs1 {
    interface Interface2 {
      field1: FooBar$1;
    }
  }
}
declare namespace Ns2 {
  module SubNs1 {
    interface Interface1 {
      field1: F1Ns1.SubNs1.Interface1;
    }
  }
}
declare namespace Ns2 {
  module SubNs1 {
    interface Interface2 {
      field1: F1Ns1.SubNs1.Interface2;
    }
  }
}
declare namespace Ns2$1 {
  module SubNs1 {
    interface Interface1 {
      field1: F2Ns1.SubNs1.Interface1;
    }
  }
}
declare namespace Ns2$1 {
  module SubNs1 {
    interface Interface2 {
      field1: F2Ns1.SubNs1.Interface2;
    }
  }
}
export interface Int {
  f1: F1Ns1.SubNs1.Interface1;
  f2: F2Ns1.SubNs1.Interface1;
}

export {
  F1Ns1,
  Ns2 as F1Ns2,
  F2Ns1,
  Ns2$1 as F2Ns2,
};
