// Generated by @qlik/dts-bundler@development

type TypeName = string | number;
interface InterfaceName {
  prop: number;
  prop2: TypeName;
}
export declare function func2({ prop: prop3 }?: InterfaceName): TypeName;
export declare function func({ prop }?: InterfaceName): TypeName;
