// Generated by @qlik/dts-bundler@development

interface Level3Type {
  value: string;
}
// Level2Type is an interface that includes a nested Level3Type
export interface Level2Type {
  nested: Level3Type;
}
/**
 * A Local helper type for internal use.
 */
type LocalHelper = {
  help(): void;
};
export interface Level1 {
  data: Level2Type;
  helper: LocalHelper;
}
