// Generated by @qlik/dts-bundler@development

import { OtherLib } from "other-lib";

export interface Combined {
  local: LocalHelper;
  otherLocal: OtherLocalHelper;
  lib: LibType;
  other: OtherLib;
}
