import ts from "typescript";
import pkg from "../package.json" assert { type: "json" };
import type { TypeRegistry } from "./registry.js";
import type { ExternalImport, TypeDeclaration } from "./types.js";

const version = (pkg as { version?: string }).version ?? "development";

export class OutputGenerator {
  private registry: TypeRegistry;
  private usedDeclarations: Set<symbol>;
  private usedExternals: Map<string, Set<ExternalImport>>;
  private nameMap: Map<string, string>;
  private options: {
    noBanner?: boolean;
    sortNodes?: boolean;
    umdModuleName?: string;
    includeEmptyExport?: boolean;
    allowedTypesLibraries?: string[];
    importedLibraries?: string[];
    referencedTypes?: Set<string>;
  };

  constructor(
    registry: TypeRegistry,
    usedDeclarations: Set<symbol>,
    usedExternals: Map<string, Set<ExternalImport>>,
    options: {
      noBanner?: boolean;
      sortNodes?: boolean;
      umdModuleName?: string;
      includeEmptyExport?: boolean;
      allowedTypesLibraries?: string[];
      importedLibraries?: string[];
      referencedTypes?: Set<string>;
    } = {},
  ) {
    this.registry = registry;
    this.usedDeclarations = usedDeclarations;
    this.usedExternals = usedExternals;
    this.nameMap = new Map();
    this.options = options;
  }

  generate(): string {
    const lines: string[] = [];

    const banner = !this.options.noBanner ? `// Generated by @qlik/dts-bundler@${version}` : null;
    const referenceDirectives = this.generateReferenceDirectives();
    const externalImports = this.usedExternals.size > 0 ? this.generateExternalImports() : [];

    this.buildNameMap();
    const declarations = this.generateDeclarations();

    const umdDeclaration = this.options.umdModuleName ? [`export as namespace ${this.options.umdModuleName};`] : [];
    const emptyExport = this.options.includeEmptyExport ? ["export {};"] : [];

    const appendSection = (section: string[]): void => {
      if (section.length === 0) return;
      if (lines.length > 0) lines.push("");
      lines.push(...section);
    };

    if (banner) {
      lines.push(banner);
    }

    appendSection(referenceDirectives);
    appendSection(externalImports);
    appendSection(declarations);
    appendSection(umdDeclaration);
    appendSection(emptyExport);

    return `${lines.join("\n")}\n`;
  }

  private buildNameMap(): void {
    for (const id of this.usedDeclarations) {
      const declaration = this.registry.getDeclaration(id);
      if (declaration && declaration.name !== declaration.normalizedName) {
        const key = `${declaration.sourceFile}:${declaration.name}`;
        this.nameMap.set(key, declaration.normalizedName);
      }
    }
  }

  private generateExternalImports(): string[] {
    const lines: string[] = [];
    const sortedModules = Array.from(this.usedExternals.keys()).sort();

    for (const moduleName of sortedModules) {
      const imports = Array.from(this.usedExternals.get(moduleName) ?? []);
      if (imports.length === 0) continue;

      const isTypeOnly = imports.every((imp) => imp.isTypeOnly);
      const typePrefix = isTypeOnly ? "type " : "";

      const hasNamespace = imports.some((imp) => imp.normalizedName.startsWith("* as "));

      if (hasNamespace) {
        const importList = imports.map((imp) => imp.normalizedName).sort();
        lines.push(`import ${typePrefix}${importList.join(", ")} from "${moduleName}";`);
      } else {
        const importList = imports
          .map((imp) => imp.normalizedName)
          .filter((name) => !name.startsWith("default as "))
          .sort();

        if (importList.length > 0) {
          lines.push(`import ${typePrefix}{ ${importList.join(", ")} } from "${moduleName}";`);
        }
      }
    }

    return lines;
  }

  private generateDeclarations(): string[] {
    const lines: string[] = [];

    const sorted = this.topologicalSort();
    const ordered = this.options.sortNodes
      ? [...sorted].sort((a, b) => {
          const rank = OutputGenerator.getSortRank(a) - OutputGenerator.getSortRank(b);
          if (rank !== 0) return rank;
          return a.normalizedName.localeCompare(b.normalizedName);
        })
      : sorted;

    for (const declaration of ordered) {
      let text = declaration.getText();

      if (!declaration.isExported && text.includes("export ")) {
        text = OutputGenerator.stripExportModifier(text);
      }

      text = this.replaceRenamedReferences(text, declaration);

      lines.push(text);
    }

    return lines;
  }

  private static stripExportModifier(text: string): string {
    return text.replace(/^((?:\s*(?:\/\*[\s\S]*?\*\/\s*|\/\/[^\n]*\n\s*)*))export\s+/, "$1");
  }

  private topologicalSort(): TypeDeclaration[] {
    const sorted: TypeDeclaration[] = [];
    const visited = new Set<symbol>();
    const visiting = new Set<symbol>();

    const visit = (id: symbol): void => {
      if (visited.has(id)) return;
      if (visiting.has(id)) {
        return;
      }

      visiting.add(id);
      const declaration = this.registry.getDeclaration(id);

      if (declaration) {
        for (const depId of declaration.dependencies) {
          if (this.usedDeclarations.has(depId)) {
            visit(depId);
          }
        }

        visiting.delete(id);
        visited.add(id);
        sorted.push(declaration);
      }
    };

    const used = Array.from(this.usedDeclarations);
    const exported = used.filter((id) => {
      const decl = this.registry.getDeclaration(id);
      return decl && decl.isExported;
    });
    const nonExported = used.filter((id) => {
      const decl = this.registry.getDeclaration(id);
      return decl && !decl.isExported;
    });

    for (const id of nonExported) {
      visit(id);
    }
    for (const id of exported) {
      visit(id);
    }

    return sorted;
  }

  private replaceRenamedReferences(text: string, declaration: TypeDeclaration): string {
    let result = text;

    if (declaration.name !== declaration.normalizedName) {
      const regex = new RegExp(`\\b(type|interface|class|enum)\\s+${declaration.name}\\b`, "g");
      result = result.replace(regex, `$1 ${declaration.normalizedName}`);
    }

    for (const depId of declaration.dependencies) {
      const depDecl = this.registry.getDeclaration(depId);
      if (depDecl && depDecl.name !== depDecl.normalizedName) {
        const regex = new RegExp(`\\b${depDecl.name}\\b(?![_])`, "g");
        result = result.replace(regex, depDecl.normalizedName);
      }
    }

    for (const [moduleName, importNames] of declaration.externalDependencies.entries()) {
      const moduleImports = this.registry.externalImports.get(moduleName);
      if (!moduleImports) continue;

      for (const importName of importNames) {
        const externalImport = moduleImports.get(importName);
        if (!externalImport) continue;

        const originalName = OutputGenerator.extractImportName(externalImport.originalName);
        const normalizedName = OutputGenerator.extractImportName(externalImport.normalizedName);

        if (originalName !== normalizedName) {
          const regex = new RegExp(`\\b${originalName}\\b(?![_])`, "g");
          result = result.replace(regex, normalizedName);
        }
      }
    }

    return result;
  }

  private static extractImportName(importStr: string): string {
    if (importStr.startsWith("default as ")) {
      return importStr.replace("default as ", "");
    }
    if (importStr.startsWith("* as ")) {
      return importStr.replace("* as ", "");
    }
    if (importStr.includes(" as ")) {
      const parts = importStr.split(" as ");
      return parts[1].trim();
    }
    return importStr;
  }

  private static getSortRank(declaration: TypeDeclaration): number {
    const node = declaration.node;
    if (ts.isInterfaceDeclaration(node)) return 1;
    if (ts.isTypeAliasDeclaration(node)) return 2;
    if (ts.isClassDeclaration(node)) return 3;
    if (ts.isEnumDeclaration(node)) return 4;
    if (ts.isModuleDeclaration(node)) return 5;
    return 10;
  }

  private generateReferenceDirectives(): string[] {
    const directives: string[] = [];
    const { referencedTypes, allowedTypesLibraries } = this.options;

    if (!referencedTypes || referencedTypes.size === 0 || !allowedTypesLibraries) {
      return directives;
    }

    // Generate triple-slash directives for types that are both:
    // 1. Referenced with preserve="true" in source files
    // 2. Listed in allowedTypesLibraries
    const sortedTypes = Array.from(referencedTypes).sort();
    for (const typeName of sortedTypes) {
      if (allowedTypesLibraries.includes(typeName)) {
        directives.push(`/// <reference types="${typeName}" />`);
      }
    }

    return directives;
  }
}
