// Generated by @qlik/dts-bundler@development

import { default as myClass5 } from "package-with-default-export";

declare function _default(second: number);
declare function _default$1(first: number);
declare class _default$2 {
  second: number;
}
declare class _default$3 {
  first: number;
}
declare const _default$4: 0;
declare const _default$5: { type: string };
declare const _default$6: "";

export {
  _default$3 as myClass1,
  _default$3 as myClass2,
  _default$2 as myClass3,
  _default$2 as myClass4,
  myClass5,
  _default$1 as myFunc1,
  _default$1 as myFunc2,
  _default as myFunc3,
  _default as myFunc4,
  _default$4 as number,
  _default$5 as object,
  _default$6 as string,
};
